<?php
return array(
        'host'=>array(
                'label'=>self::lang('host'),
                'required'=>true,
                'error'=>false,
                'value'=>'localhost'
        ),
        'login'=>array(
                'label'=>self::lang('login'),
                'required'=>true,
                'error'=>false,
                'value'=>'',
        ),
        'password'=>array(
                'label'=>self::lang('password'),
                'required'=>false,
                'error'=>false,
                'value'=>'',
        ),
        'dbname'=>array(
                'label'=>self::lang('dbname'),
                'required'=>true,
                'error'=>false,
                'value'=>'',
        )
);