<?php
return array(
		'admin_email'=>array(
				'label'=>self::lang('admin_email'),
				'required'=>true,
				'error'=>false,
				'value'=>'',
		),
		'sys_email'=>array(
				'label'=>self::lang('sys_email'),
				'required'=>true,
				'error'=>false,
				'value'=>'',
		),
		'slogan'=>array(
				'label'=>self::lang('slogan'),
				'required'=>false,
				'error'=>false,
				'value'=>self::lang('slogan_value'),
		),
);